sudo: required
language: generic

env:
  global:
    - secure: "afYxTSVkpQw4zfKNzfR5g1e4AWti/mgzcz3rFuMAv0fIzm6/vejV7p9WkW4GR3GTI+8C4I3A8FK/nQCBsLvOcGeXDRku16kheRiRFTfWk9Kt5LtaBaEHnVaIijVFGZ3Amr6kGZ8qlmu6ef1xhLbKdun86oTV8JLU8eLYjyJqmF4eu4pf+a4Nxj59xxLqhcM/TtoBNP/OtpB2fZrNwY0x0zD10gHgC+8YQrGTuR/jab0rjhzNfv5E4lnb86DE7nF9KPysdoTGcCqfwO+gC7ooh1BD/EKUpNmI7maNuiMSKFqiToG1PMK1G8eDjlq25vaJl2amTKRxgz7ZgvL0GiStPERJVK5kPu3JJ+D4fgjIck9qJ2B43u2fF9R2Kv3A1Q6nCXNkFTqlOAfUWM4Cn/FIzDP86K3Vuz/1f1LzAhSvIl0JZwXi8y+f9kDZaCd2H0fWFlDdp07BdB3NafTZd3OjYE9bGKIywUfdblwMXl1PAb1qJSQhSjxzUzBH1DBlWsDTvIgvX+V2j1zGumwC87x0+6F21Q0+1ZjutMnOdMqnTBJUSoINsfKOVHQlbES9FWb5afgZsp1NRP5UuyoygOKalDU6Aw+33zQao8azb3KMYBu/jpebN9f5+5ftPBTMqaRIqbxyBhKxEi/4P0YHRdmEb4XqwasxuJRmZIRrls5Gmzg="
    - secure: "nRtKXRqV6HhU3VbiTtWeHB0zveAk8yXm97KACXKVVOLlUfO7OF9iwrMoNFt7wRDDXNUztXOXZ7mQfZXJ3z9/Z/T7EtKiBV2YNktTXqdA2fHMGpyHyY9LftJV1OQMNAoUWJ4y5xINtAmB1CrkgN4jtpoNi4HIwJ5CiCGpJnHkK0pHBuL2NGl6aUwIR1ZJvSkSclXh5v+U9fq6/zsybjwFBS8v3CooP9N0hFYvMLApeBiPAEIKU2oAGWCUCL7FhMjZ6jOOHU0+aK8mJt/o6tMEyAbmFVkg1nXr+5UAU5AtgSJYW0+61Epww2tSMjYgacQ9KDCtBNWmDoZpy9EB/x+oLuG1bBRZi+6+9p4bZH2iQDzPPbULIXaffs6Ru9y6o5wcJNVFVegAzUQv8yNcksWNjncyOpvJZq7kQYVjFi/dzkxMilvAqp1p+OiQ1R8Rk6W/XqTn36bIADMGTCLfHwogJHUQnoMjZndof5HytlMCIrzNuCK1xlB+dzZZDrNatx5zhzuCHerJ6F2Ydbu3ASA5r8ifHLDf9EDps5sHNTP3IpiN2V/NKK4myi8fW7UwjmshaLG7pmKjZVCZpMkA/CsGew3UVFWl1PXB6aKS7XdNqhA5zan0mk42GSnxp6HRPdXBqVbhOU8MjB46I2cnXBvzOnxsRImGJtDJV0CCU8YCnl8="

services:
  - docker

before_install:
  - docker build -t avalon-front .
  - docker tag avalon-front $DOCKER_USERNAME/avalon-front

after_script:
  - docker images

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  provider: script
  script: docker push sopretty/avalon-front
  on:
    branch: master
