version: '3'
services:
  rethinkdb:
    image: rethinkdb
    ports:
    - "8081:8080"
    - "28015:28015"
    - "29015:29015"
    volumes:
    - AVALON-RETHINKDB-DATA:/data

volumes:
  AVALON-RETHINKDB-DATA:
