name: Build docker image and publish it 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t avalon-front .
    - name: Tag the Docker image
      run: docker tag avalon-front ${{ secrets.$DOCKER_USERNAME }}/avalon-front:master
    - name: login docker
      run: echo ${{ secrets.$DOCKER_PASSWORD }} | docker  login -u ${{ secrets.$DOCKER_USERNAME }} --password-stdin
    - name: push to docker hum
      run: docker push sopretty/avalon-front
